### ISSUE TITLE
Preprocess2 becoming OT default

### ISSUE THREAD

**Issue by kirkilj** [jason-fox/fox.jason.prismjs#15]
Hi @jason-fox,

Jarno is working on making preprocess2 map-first processing the default. I mentioned in the monthly contributor call that I'd reach out to you about your various plugins and if they'd be affected by such a switch-over. Roger Sheen mentioned that you stay on top of OT changes, but this one is a major refactoring and may affect existing OT plugins potentially. We rely on the passthrough plugin in several places and are going to evaluate the prismjs plugin as well.

Best Regards,

John

**Comment by jason-fox** [comment]
4.2 was tested with ff4a326 - no major issues found. Tests were updated 1e5a8e9 but the changes were purely cosmetic due to changes in DITA processing. No issues found with  `preprocess2`

Some other plugins were found to be using extension points not supported by  `preprocess2` and they have been updated and rereleased: https://github.com/dita-ot/registry/pull/150
